# Plugins
remote_theme: "Legolas-PRC/minimal-mistakes@v1.0"
plugins: # previously gems
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-include-cache

minimal_mistakes_skin    : "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# 站点全局配置

locale: "zh-CN" # 本地化
title: "陈钱的blog" # 站点title
subtitle: "welcome to my blog"

name: "陈钱" # 作者名

description: "this is my blog" # 站点描述

URL: # protocol+hostname

baseurl: # 所在的子目录

repository: # 项目的仓库名:"username/repo-name"

teaser: # 可在yml中其他地方被用到的图片，path：/assets/images/。。。

logo: # 站点标题前的logo,path：/assets/images/。。。

masthead_title: # 顶栏的标题


include:
  - _pages

# Defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      # share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true