# Plugins
remote_theme: Legolas-PRC/minimal-mistakes@v1.0
plugins: # previously gems
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-include-cache

minimal_mistakes_skin    : "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# 站点全局配置
  # 本地化
  locale: zh-CN
  # 站点title
  title: "陈钱的blog"
  subtitle: 
  # 作者名
  name: 陈钱
  # 站点描述
  description: this is my blog
  # protocol+hostname
  URL: 
  # 所在的子目录
  baseurl: 
  # 项目的仓库名:"username/repo-name"
  repository: 
  # 可在yml中其他地方被用到的图片，path：/assets/images/。。。
  teaser:
  # 站点标题前的logo,path：/assets/images/。。。
  logo: 
  # 顶栏的标题
  masthead_title: 


  # Defaults
defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true